# Generated by Django 3.2 on 2022-06-16 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Arcanist', 'Arcanist'), ('Avenging Madman', 'Avenging Madman'), ('Exorcist', 'Exorcist'), ('Witch Hunter', 'Witch Hunter'), ('Telepath', 'Telepath'), ('Archeologist', 'Archeologist')], max_length=50)),
                ('description', models.TextField(default='')),
                ('vita_base', models.IntegerField(default=0)),
                ('power_base', models.IntegerField(default=0)),
                ('might_base', models.IntegerField(default=0)),
                ('damage_base', models.IntegerField(default=0)),
                ('stride_base', models.IntegerField(default=0)),
                ('defense_base', models.IntegerField(default=0)),
                ('archeology_base', models.IntegerField(default=0)),
                ('awareness_base', models.IntegerField(default=0)),
                ('ecology_base', models.IntegerField(default=0)),
                ('faith_base', models.IntegerField(default=0)),
                ('nerve_base', models.IntegerField(default=0)),
                ('occult_base', models.IntegerField(default=0)),
                ('speech_base', models.IntegerField(default=0)),
                ('trickery_base', models.IntegerField(default=0)),
                ('special_ability', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Focus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_to_focus', models.CharField(choices=[('Arcanist', 'Arcanist'), ('AvengingMadman', 'Avenging Madman'), ('Exorcist', 'Exorcist'), ('WitchHunter', 'Witch Hunter'), ('Telepath', 'Telepath'), ('Archeologist', 'Archeologist')], default='', max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('benefit', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MysticKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NegConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PosConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StoryMarkers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('current_story', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('character_name', models.CharField(default='character', max_length=50)),
                ('lore', models.IntegerField(default=0)),
                ('coin', models.IntegerField(default=0)),
                ('description', models.TextField(default='description')),
                ('special_ability', models.TextField(default='special ability')),
                ('vita_base', models.IntegerField(default=0)),
                ('vita_items', models.IntegerField(default=0)),
                ('vita_mod', models.IntegerField(default=0)),
                ('power_base', models.IntegerField(default=0)),
                ('power_items', models.IntegerField(default=0)),
                ('power_mod', models.IntegerField(default=0)),
                ('might_base', models.IntegerField(default=0)),
                ('might_items', models.IntegerField(default=0)),
                ('might_mod', models.IntegerField(default=0)),
                ('damage_items', models.IntegerField(default=0)),
                ('damage_mod', models.IntegerField(default=0)),
                ('stride_items', models.IntegerField(default=0)),
                ('stride_mod', models.IntegerField(default=0)),
                ('defense_items', models.IntegerField(default=0)),
                ('defense_mod', models.IntegerField(default=0)),
                ('damage_base', models.IntegerField(default=0)),
                ('stride_base', models.IntegerField(default=0)),
                ('defense_base', models.IntegerField(default=0)),
                ('archeology_items', models.IntegerField(default=0)),
                ('archeology_mod', models.IntegerField(default=0)),
                ('awareness_items', models.IntegerField(default=0)),
                ('awareness_mod', models.IntegerField(default=0)),
                ('ecology_items', models.IntegerField(default=0)),
                ('ecology_mod', models.IntegerField(default=0)),
                ('faith_items', models.IntegerField(default=0)),
                ('faith_mod', models.IntegerField(default=0)),
                ('nerve_items', models.IntegerField(default=0)),
                ('nerve_mod', models.IntegerField(default=0)),
                ('occult_items', models.IntegerField(default=0)),
                ('occult_mod', models.IntegerField(default=0)),
                ('speech_items', models.IntegerField(default=0)),
                ('speech_mod', models.IntegerField(default=0)),
                ('trickery_items', models.IntegerField(default=0)),
                ('trickery_mod', models.IntegerField(default=0)),
                ('archeology_base', models.IntegerField(default=0)),
                ('awareness_base', models.IntegerField(default=0)),
                ('ecology_base', models.IntegerField(default=0)),
                ('faith_base', models.IntegerField(default=0)),
                ('nerve_base', models.IntegerField(default=0)),
                ('occult_base', models.IntegerField(default=0)),
                ('speech_base', models.IntegerField(default=0)),
                ('trickery_base', models.IntegerField(default=0)),
                ('wanted', models.BooleanField(default=False)),
                ('infected', models.IntegerField(default=0)),
                ('keywords', models.TextField(blank=True)),
                ('mystic_knowledge', models.TextField(blank=True)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='api.character')),
                ('party', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.party')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='focus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.focus'),
        ),
        migrations.AddField(
            model_name='character',
            name='keywords',
            field=models.ManyToManyField(to='api.Keyword'),
        ),
        migrations.AddField(
            model_name='character',
            name='mystic_knowledge',
            field=models.ManyToManyField(to='api.MysticKnowledge'),
        ),
    ]
